import creatures.gods.MainGod;
import enums.*;
import creatures.humans.*;
import objects.*;

import java.util.Arrays;

public class Main {
    public static void main(String[] args) {
        Human[] porters = new Human[4];
        MainGod mainGod = new MainGod("Бог");
        Ellie ellie = new Ellie("Элли", 8, 3, 0);
        Louis louis = new Louis("Луис", 28, 2, 0);
        Jude jude = new Jude("Джуд", 30, 2, 0);
        Hedge hedge = new Hedge("Гэдж", 2, 0, 0);
        Norma norma = new Norma("Норма", 40, 0, 0);
        Parishioner parishioners = new Parishioner("Прихожане", 0, 0, 0);
        Reverend reverendLaughing = new Reverend("Преподобный Лафлин", 40, 0, 0, mainGod);
        JudeNephew firstNephew = new JudeNephew("Первый племянник Джуда", 30, 0, 0);
        JudeNephew secondNephew = new JudeNephew("Второй племянник Джуда", 31, 0, 0);
        NormaBrother normaBrother = new NormaBrother("Брат Нормы", 25, 0, 0);
        BlackSuit blackSuit = new BlackSuit();
        BlueDress blueDress = new BlueDress();
        System.out.println("Непонимание Элли: " + ellie.getConfusion());
        System.out.println("Красота Элли: " + ellie.getBeauty());
        System.out.println("Усталость Элли: " + ellie.getFatigue());
        System.out.println("Усталость Луиса: " + louis.getFatigue());
        System.out.println("Удивление Луиса: " + louis.getSurprise());
        System.out.println("Слепота из-за любви Луиса: " + louis.getBlindness());
        ellie.sit(ellie);
        louis.sit(ellie);
        ellie.wear(blueDress.getName());
        louis.performHear(ellie);
        ellie.be(Locations.CHURCH.getName());
        ellie.be(Locations.FUNERAL.getName());
        louis.seeFromSide(Adjectives.USUAL.getName(), ellie, hedge);
        louis.seeFromSide(Adjectives.RARELY.getName(), ellie, hedge);
        louis.think(ellie);
        jude.wear("");
        jude.wear(blackSuit.getName());
        louis.seeOnly(jude);
        jude.lean(ellie);
        jude.kiss(ellie, Nouns.FOREHEAD.getName());
        ellie.openEyes(jude, norma);
        reverendLaughing.pray(norma, mainGod);
        reverendLaughing.speak("");
        ellie.grabPerson(louis);
        louis.whisper("message1");
        porters[0] = louis;
        norma.grabAndCarry(porters);
        louis.almostSit();
        louis.putHand(ellie);
        louis.whisper("message2");
        porters[1] = firstNephew;
        porters[2] = secondNephew;
        porters[3] = normaBrother;
        norma.grabAndCarry(porters);
        ellie.speak("phrase1");
        normaBrother.comeClose(jude);
        firstNephew.comeClose(jude);
        secondNephew.comeClose(jude);
        louis.lookBack(normaBrother, firstNephew, secondNephew,jude);
        louis.comeClose(jude);
        parishioners.goAway();
        parishioners.cry();
        louis.speak("phrase1");
        ellie.speak("phrase2");
        louis.speak("phrase2");
        ellie.catchHand(louis);
        ellie.speak("phrase3");
        louis.speak("phrase3");
        ellie.whisper("message2");
    }
}